apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: entando-tls-secret
  namespace: entando
spec:
  secretName: entando-tls-secret
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-cluster
  dnsNames:
    - CHANGE_THIS
  usages:
    - digital signature
    - key encipherment
